name: CI/CD Pipeline

on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск тестов
      run: pytest

  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Проверка наличия README.md
      run: test -f README.md && echo "Документация найдена" || (echo "README.md отсутствует" && exit 1)
    - name: Сохранение документации как артефакта
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: README.md
